jorgebucaran/fisher

README.md

We have moved into slack room from gitter

We have moved into slack room from gitter

---

_site/index.html

Great project.
Just noticed that the link on the website to the docs was slightly off.

Fix link to man7 docs

---

README.md

Seems you forgot to update the link.

Fix README link.

---

functions/fisher_help.fish
functions/fisher_install.fish
functions/fisher_search.fish
functions/fisher_uninstall.fish
functions/fisher_update.fish
test/fixtures/help/usage.txt

[#84] Beautify -h (4×' ', 15×opt, desc)

---

man/man1/fisher-help.md
man/man1/fisher-install.md
man/man1/fisher-search.md
man/man1/fisher-uninstall.md
man/man1/fisher-update.md
man/man1/fisher.md
man/man1/getopts.md
man/man5/fisher-fishfile.md
man/man7/fisher-commands.md
man/man7/fisher-config.md
man/man7/fisher-faq.md
man/man7/fisher-plugins.md
man/man7/fisher-tour.md

Sorry for the late commit, I don't have the time to read through all the docs, I just skim though it and fix everything quickly.

[#129] Beautify man pages

---

README.md

Small change, but for complete accuracy :smile:

Correction of URL in README

---

functions/__fisher_plugin_fetch.fish

when symbolic link target_file has moved test -e $path will return false for issues #182

use test -L and -e to judge whether file exists.

---

Makefile

Credits to @tuvistavie
https://github.com/fisherman/fisherman/issues/16#issuecomment-201699699
closes 16

Fix broken config.fish symlinks during install

---

docs/zh-CN/README.md

add 2.0.0 Chinese README.md

---

docs/ko-KR/README.md

Add Korean docs for 2.0

---

docs/zh-CN/README.md

@bucaran update Chinese README.md

:cn: README.md update

---

README.md
docs/ru-RU/README.md

I noticed, that there are no more links to the online search..

Updated Russian docs

---

README.md

Add a FAQ section for how to resolve ls-remote being rate limited/rejected by the GitHub api when accessing anonymously.

Add FAQ for resolving github api token issues

---

README.md

see wiki page [Français].
[Français]: https://github.com/fisherman/fisherman/wiki/Fran%C3%A7ais

add French translation

---

README.md

Add example of using `ls-remote --format` to display additional info about available plugins.

Explain `ls-remote --format` option

---

fisher.fish

Check commits for details
Closes #362

Improve warnings about fish versions

---

README.md
fisher.fish

Document how to install branches and tags

---

fisher.fish

Fix https://github.com/fisherman/fisherman/issues/389

Escape "$file" in the warning message.

---

fisher.fish

This solves a few issues that prevents fisher from workin in [termux](https://termux.com/):
* Use `>&2` to redirect to stderr (this is more portable than `/dev/stderr`): https://unix.stackexchange.com/a/274044/68749
* Use `/proc/self/fd/2` for `__fisher_stderr` (only if the OS is termux, to minimize risk)
* Use `$PREFIX` to check which OS is running (if someone has a better idea, I'm sure there's a better way)
* Use `mandoc` directly for `fisher help` on termux, because it runs the [busybox](https://busybox.net/about.html) version of `man` which does not support `-P`
I have tested with fish `2.5.0` on:
* `Termux`
* `Mint` (a recent version)
* `Ubuntu 16.04.2`
I tested `fisher`, `fisher z`, `fisher help` and `fisher update`.
I think another pair of eyes would be warranted since I have …

Termux compatibility

---

fisher.fish

fix: replace ln with cp; don't hardlink; close #470

---

fisher.fish

Read fishfile from $fisher_path instead of $fish_config

---

README.md

Remove non-existing --event argument for function.
Source: https://fishshell.com/docs/current/commands.html#function

README: Update function option in conf.d

---

README.md

As mentioned in https://github.com/jorgebucaran/fisher/issues/461#issuecomment-427638774, a link to the awesome-fish-shell list will help people find packages.

docs: Link to awesome-fish-shell list

---

fisher.fish

"Make curl display information on stdout after a completed transfer."
Intended for interactive sessions, doesn't like pipes very much

Make curl ignore the "-w" argument. Fixes #530

---

README.md

Change --event to --on-event

---

README.md

Document `fisher`'s ownership of `$XDG_CONFIG_HOME/fisher`.

Update the README 

---

fisher.fish

Resolves https://github.com/jorgebucaran/fisher/issues/565

Fix `_fisher_parse` function for BusyBox awk

---

README.md

use full path instead of git.io

README.md use full path instead of git.io

---

README.md
functions/fisher.fish

Add the possibility to add plugins from gitlab. Resolves #657.

Add GitLab support

---

functions/fisher.fish

Support themes
