jorgebucaran/fisher

README.md
The manpages are `fisher(1)` and `fisher(7)`, not `fisherman(1)` and `fisherman(7)`.
=> Update README.md for manpage names

functions/__fisher_file_remove.fish, functions/__fisher_index_update.fish, functions/__fisher_key_bindings_disable.fish, functions/__fisher_key_bindings_enable.fish, functions/__fisher_plugin_enable.fish, functions/__fisher_plugin_link.fish, functions/__fisher_plugin_unlink.fish, functions/fisher_install.fish, functions/fisher_uninstall.fish, functions/wait.fish
By using `command` we ensure that we always end up calling the external
binary and don't get caught by user aliasses, functions or other
magic.
Closes #79
This is a find-replace powered fix, I might have missed something. I purposefully didn't alter the tests so that we could catch any discrepancies.
=> Use command when calling non-builtins

functions/__fisher_plugin_validate.fish
of the next line has problems, at least on my machine running cygwin.
It produced an error like this:
~/.local/share/fisherman/functions/__fisher_plugin_validate.fish (line
42):                 | sed -E "
^ from sourcing file
~/.local/share/fisherman/functions/__fisher_plugin_validate.fish
called on standard input
This change simply eliminates the \ line continuation and instead
concatenates with the next line.  It seems simple enough and avoids
this problem, making it work on cygwin.
=> For some reason a \ line continuation followed by a | at the beginning

fisher.fish
Sorry for writing in Japanese.
日本語で失礼します
`fisher ls [plugins]` コマンドが、正常にディレクトリツリーを表示しないので、修正しています
- 修正前
```fish
> fisher ls rbenv
/Users/username/.config/fisherman/rbenv
completions/
rbenv.fish
rbenv.fish
rbenv.fish
LICENSE
README.md
```
- 修正後
```fish
> fisher ls rbenv
/Users/username/.config/fisherman/rbenv
completions/
rbenv.fish
conf.d/
rbenv.fish
functions/
rbenv.fish
LICENSE
README.md
```
=> ``fisher ls [plugins]`` command fix

fisher.fish
OpenBSD's ````ln```` does not support the -F flag. This PR drops the flag, only for OpenBSD, so as not to change the behavior for other OSes.
=> eliminate -F for ln for OpenBSD by abstracting ln flags

fisher.fish
in my virtual box
````bash
[root@localhost ~]# cat /etc/issue
CentOS release 6.5 (Final)
Kernel \r on an \m
````
and when i run command
````bash
fisher simple
````
i got 
````bash
Can't locate Time/HiRes.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
````
i find we use
````bash
perl -MTime::HiRes -e 'printf("%.0f\n", (Time::HiRes::time() * 1000) - '$elapsed')'
````
to get millisecond, but in my host i dont have install Time-HiRes module.  i do install with `yum install perl-Time-HiRes` so that resolve it
are there something i missing?  so just use /bin/date to replace.
code LGTM. But i'm not sure whether it's always right. maybe we should add test:)
=> use /bin/date replace perl to get get_epoch_in_ms

fisher.fish
It's a tiny little typo fix. I noticed it while reading the `__fisher_remote_index_update` function code.
=> Fixed a typo: fin_index_update_interval

fisher.fish
Examples:
- `fisher install fisherman/done@dev`
- `fisher install fisherman/done@1.1.0`
OR
- `fisher install fisherman/done:dev`
- `fisher install fisherman/done:1.1.0`
Related: #269
=> Install/Update from branch separated by : or @

fisher.fish
closes #371 
I moved the looping out of `awk` so that we can use `git` to get the exact origin url we want for each repository and feed that to the original logic.
=> Prevent additional remotes per plugin from affecting fishfile

README.md, fisher.fish
Previously, running `fisher up` would always write fisher.fish to $fish_config/completions, even if $fish_path had been set.
This branch fixes that, and updates the README to reflect the extra steps required to source snippets and discover functions and completions installed by fisherman when using $fish_path.
Refs #391
=> `fisher up` obeys $fish_path

fisher.fish
For some reason index file was generated without space after first semicolon for me.
Using awk's match() function and RLENGTH to extract substring (either with space of without) resolves https://github.com/fisherman/fisherman/issues/399.
=> improve index file parsing

README.md
I noticed that fisherman has had a logo for a long time but for some reason it doesn't show up on the GitHub home page, most likely the most-prominent, most high-traffic, face of fisherman. I hope that by adding the logo fisherman will appear more profession and gain a greater market share of users.
Note that by adding the logo on top, I displaced the original link to the plugins homepage so I incorporated the link into the one-liner description.
=> Add fisherman logo to readme

fisher.fish
- Explain how to copy, not link, files when installing plugins
- This feature was added in v2.13.3
=> Update help to be more in line with README

README.md
The `fish_function_path` must be set before sourcing the `conf.d` files because they might call functions in that path.
=> Fix config.fish example for custom paths

README.md, fisher.fish
With the addition of keybinding support for fish 2.x, fisher greatly
increases shell startup time (50-100ms in my testing). This is due to a
number of reasons, including using less-than-ideal builtins,
unconditionally running mkdir, unconditionally recreating
conf.d/fisher.fish, and checking for curl on startup (instead of when
curl is used).
This patch cuts fisher-related startup time to roughly 25ms, simplifying
the code paths as much as I am able.
The source function is removed as a compromise for speed. Fish 2.1 and
greater support `source`, and supporting fish 2.0 is not worth a hefty
speed penalty in my opinion.
curl checks have been moved to the two uses of curl -- there is some
duplication now so this may be slightly less ideal. Also, curl checks
are now done with the builtin …
=> Optimize fisher startup path

README.md
Avoid doubling paths in `fish_function_path` and `fish_complete_path`.
=> docs: fix configuration commands

fisher.fish
This allows fishfile to be a symlink, which I used to keep track of my
dotfiles in a repo, and broke after upgrading to V3.
=> Override fishfile content instead of replacing the file

README.md
The help and version commands use the "--" prefix. This updates the readme to reflect that.
=> docs: match version and help commands to actual

fisher.fish
Per issue #545, support fishfile living in $fish_config even when $fisher_path is set if desired.
Implementation details:
- Added a new `_fishfile` function
- If `$fisher_path/fishfile` exists and `$fish_config/fishfile` doesn't, then use `$fisher_path/fishfile`. Otherwise use `$fish_config/fishfile`.
- Set local variable for fishfile to call _fishfile function
=> Better fishfile location support

.github/workflows/ci.yml, .travis.yml, README.md
Migration will switch from Travis CI to GitHub Actions. This PR covers the following:
* Removal of Travis CI configuration
* Addition of Continuous Integration GitHub Action
* Addition of GitHub Action badge in README
This will close #567.
=> Switch to GitHub Actions

fisher.fish
Going by the [XDG base directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), it makes more sense to place fisher data in `XDG_DATA_HOME` rather than `XDG_CONFIG_HOME` based on fisher's current usage of the directory. This PR covers the following:
* Swap all instances of `fisher_config` with `fisher_data`, which will point to `XDG_DATA_HOME`
* Run a check (until new major version is introduced), which will perform the directory migration
I chose to keep the README as is, as most users should still avoid placing their data in `XDG_CONFIG_HOME/fisher` in case fisher will need it in the future for other reasons.
This will close #568.
=> Migrate Data to Proper XDG Directory

fisher.fish
By using curl's `-f` option, we improve the self-update mechanism by not overwriting the fisher script if the HTTP status code given to us by Github is higher than 400.
Additionally, we make sure that the exit code of the curl process must be always zero for the self-update to succeed.
The `-S` option, when used with `-s`, allows us to get an error message from curl when it fails.
A few examples:
Fixes #578
=> self-update: better network error handling

README.md
Based on my tests, in a file named `fzf.fish`
```
echo (basename (status -f) .fish){_uninstall}
fzf{_uninstall}
```
but
```
echo (basename (status -f) .fish)_uninstall
fzf_uninstall
```
So I think there's a bug in the instructions.
=> fix uninstall plugin event instructions

.github/workflows/ci.yml, README.md, completions/fisher.fish, fisher.fish
If you are in Fisher 3.x, upgrading to Fisher 4.0 will be as easy as running:
```console
fisher self-update
```
If you are new to Fisher, just use the bootstrapping script:
```console
curl -sL git.io/fisher | source && fisher install jorgebucaran/fisher
```
For all the changes and acknowledgments, read the [release notes](https://github.com/jorgebucaran/fisher/releases/tag/4.0.0) after this PR is merged. Fisher has been completely re-written to leverage fish 3.0 new features. If you want to dive into the code, see [the new `fisher.fish`](https://github.com/jorgebucaran/fisher/blob/d86a1f1da3607f3cb3de5e14a05e1af910a39d46/fisher.fish#L1-L188) here. 
If you want to study the Fisher 3.x→4.x migration strategy, [check the code here](https://github.com/jorgebucaran/fisher/blob/d86a1f1da3607f3cb …
=> Fisher 4.0

README.md
Using HTTPS would help prevent: 
* accidentally running a captive portal login screen as a fish script and sourcing it
* and other obvious security and privacy benefits of HTTPS
=> Use HTTPS for installation

functions/fisher.fish
OpenBSD's tar command unfortunately doesn't support long options (see https://man.openbsd.org/tar). Using short options ensures compatibility with OpenBSD systems.
Also see https://github.com/jorgebucaran/fisher/issues/489
=> fisher.fish: Use short-option style for tar

functions/fisher.fish
We need the -L flag because we're being redirected.
The included header is recommended by github.
closes #699
=> updated github api endpoint

README.md
The default branch of tide is for development, so if we install from the default branch we will get a warning to install v5.
https://github.com/IlanCosman/tide#installation
Suggested by https://github.com/jorgebucaran/fisher/pull/710#issuecomment-1112406509
=> Update installation command examples to correct tide installation instructions

functions/fisher.fish
`fish` may not be an available command, for example if it was installed through `brew`. Whenever I `rm -r ~/.config/fish/` on my mac (for developing Tide), I have to `fish_add_path /opt/homebrew/bin/` before I run my `fisher` command. Instead, lets just guarantee a valid command by using the path to the current instance of fish. Tide already does this and it has worked fine so far.
=> Use current fish path instead of fish command

functions/fisher.fish
I have a docker image that can install fish, but it is verison 3.0.2. The bash-compatible mechnism of `fish_path=(status fish-path) command` was not added until after 3.0.2, probably 3.1. By setting `fish_path` *earlier* in the fuction, Fisher has full compatibility with this earlier version of Fish 3.
=> Fix a compatibility issue with fish 3.0.x

functions/fisher.fish
I have a plugin which shares code for zsh and fish. I'd like to symlink this shared code file to the `functions` directory within the git repository, so that it gets installed by fisher. Unfortunately fisher does not dereference links and hence installs a broken link in this case.
This PR adds the `-L` argument to `cp` in order to dereference links on install and update.
=> Dereference links on install

README.md
Per the convo in #708, here's an update to the readme with two new sections regarding theme support.
=> Update readme to include theme instructions

README.md
Fish changed their docs, `configuration-files` anchor no longer exists, but `configuration` has a decent intro.
=> Fix fishshell.com configuration link anchor

functions/fisher.fish
This is a pretty trivial change. 
The PR adds the `command` prefix in front of the `curl` and `tar` commands to avoid alias interference.
=> prepend `command` to curl and tar

functions/fisher.fish
When `.curlrc` contains `-O` option, curl saves file to disk instead of redirecting it to stdout. thats why tar fails at next step as there is noting to extract
=> fix: ignore .curlrc file when downloading plugin's tarball

functions/fisher.fish
The fish_plugins file isn't portable across machines for local plugins because it stores the path to `$HOME`, which could be different on a different machine. This PR fixes this.
Steps to reproduce with Fisher 4.4.4:
```fish
$ fisher install $__fish_config_dir/plugins/foo
fisher install version 4.4.4
Installing /Users/mattmc3/.config/fish/plugins/foo
/Users/mattmc3/.config/fish/.fisher/functions/foo.fish
Updated 1 plugin/s
$ cat $__fish_config_dir/fish_plugins
jorgebucaran/fisher
/Users/mattmc3/.config/fish/plugins/foo
```
This PR for Fisher 4.4.5, which makes fish_plugins more portable across machines with alternative user names:
```fish
$ fisher install $__fish_config_dir/plugins/foo
fisher install version 4.4.5
Installing /Users/matt/.config/fish/plugins/foo …
```
=> Use '~' for $HOME in fish_plugins file rather than resolving path
